name: Hello
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'Otong Surotong'
      home:
        description: 'location'
        required: false
      sha:
        description: 'SHA'
        required: false
      phase:
        description: 'stag/prod'
        required: false  

jobs:
  say_hello:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.inputs.sha }}
      PHASE: ${{ github.event.inputs.phase }}
    steps:
      - name: Setup defaults
        run: |
          echo $SHA
          $SHA=${SHA:-${{ github.sha }}}
          echo $PHASE
          $PHASE=$([ $PHASE = 'prod' ] && echo 'prod' || echo 'stag')
      - name: Hello
        env:
          SHA_REF: ${{github.sha}}__${{github.ref}}
        run: |
            echo "${{github.sha}}"
            echo "${{github.ref}}"
            echo "Hello ${{ github.event.inputs.name }}!"
            echo "- in ${{ github.event.inputs.home }}!"
            echo $SHA
            echo $PHASE
            
