name: Hello
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'Otong Surotong'
      home:
        description: 'location'
        required: false
      sha:
        description: 'SHA'
        required: false
      phase:
        description: 'stag/prod'
        required: false  

jobs:
  say_hello:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      PHASE: ${{ github.phase }}
    steps:
      - name: Setup SHA
        if: github.event.inputs.sha
        env:
          SHA: ${{ github.sha }}
      - name: Setup phase
        if: github.event.inputs.phase
        env:
          PHASE: github.event.inputs.phase        
      - name: Hello
        env:
          SHA_REF: ${{github.sha}}__${{github.ref}}
        run: |
          echo "${{github.sha}}"
          echo "${{github.ref}}"
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
          echo $SHA
          echo $PHASE
        shell: bash
            
