name: Main
on:
  push:
    branches: 
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # ! It is important option beacuse the action will take diff between HEAD and HEAD^
          fetch-depth: 2
      - name: test git diff
        id: get-services
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "::set-env name=SERVICES::$(echo $(git diff --name-only HEAD^ | cut -d/ -f1 | sort -u | tr '\n' ',' | sed 's/,$/\n/'))"
          
      - name: dispatch event
        run: |
          echo $SERVICES
          curl \
            --request POST \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/hello.yml/dispatches \
            --data '{ "ref":"${{ github.ref }}" }'
      - name: testing output
        run: echo $SERVICES
        
          
        
      
      
