name: Main
on:
  push:
    branches: 
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        git diff --name-only HEAD^ | cut -d/ -f1 | sort -u | tr '\n' ',' | sed 's/,$/\n/' > projects
        cat projects
    - id: file_changes
      name: File Changes Action
      uses: trilom/file-changes-action@v1.2.4
    - run: | 
        echo ${{ steps.file-change.outputs.files }}
        echo ${{ steps.file-change.outputs.files }} | sort -u | tr '\n' ',' | sed 's/,$/\n/'
      
      
