name: Main
on:
  push:
    branches: 
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # ! It is important option beacuse the action will take diff between HEAD and HEAD^
          fetch-depth: 2
      - name: Check updates
        id: check_folder
        uses: datamonsters/check-folder-updated-action@master
        with:
          folder: path/folder[/file]
      - name: Your target step
        if: steps.check_folder.outputs.has_changes == 'Yes'
        run: echo "Hello world!" 
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          git diff --name-only HEAD^ | cut -d/ -f1 | sort -u | tr '\n' ',' | sed 's/,$/\n/' > projects
          cat projects
      - id: file_changes
        name: File Changes Action
        uses: trilom/file-changes-action@v1.2.4
      - run: | 
          echo ${{ steps.file-change.outputs.files }}
          echo ${{ steps.file-change.outputs.files }} | sort -u | tr '\n' ',' | sed 's/,$/\n/'
        
      
      
