name: Main
on:
  push:
    branches: 
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # ! It is important option beacuse the action will take diff between HEAD and HEAD^
          fetch-depth: 2
      - name: test git diff
        id:
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "::set-env name=SERVICES::$(echo $(git diff --name-only HEAD^ | cut -d/ -f1 | sort -u | tr '\n' ',' | sed 's/,$/\n/'))
          
      - name: dispatch event
        run: |
          cat projects
          curl \
            --request POST \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/hello.yml/dispatches \
            --data '{ "ref":"${{ github.ref }}" }'
      - name: Workflow Dispatch
        # You may pin to the exact commit or the version.
        # uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          # Name or ID of workflow to run
          workflow: hello.yml
          # GitHub token with repo write access, can NOT use secrets.GITHUB_TOKEN, see readme
          token: ${{ secrets.ACCESS_TOKEN }}
          
        
      
      
