name: Main
on:
  push:
    branches: 
      - master
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # ! It is important option beacuse the action will take diff between HEAD and HEAD^
          fetch-depth: 2
      - name: test git diff
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          git diff --name-only HEAD^ | cut -d/ -f1 | sort -u | tr '\n' ',' | sed 's/,$/\n/' > projects
          cat projects
      - name: dispatch event
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/workflows/hello/dispatches \
            -d '{"ref":"master"}'
        
      
      
